interval: 1800 # 監視周期

slack:
  channel: "#price" # Bot が投稿するチャンネル
  error_channel: "#error" # エラーが続いた場合に Bot が投稿するチャンネル
  bot_token: xoxb-123456789012-1234567890123-XXXXXXXXXXXXXXXXXXXXXXXX # Bot のトークン

# PA-API で価格を取得するための設定
amazon:
  associate: XXXXXX-22
  access_key: XXXXXXXXXXXXXXXXXXXX
  secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  host: webservices.amazon.co.jp
  region: us-west-2

liveness:
  file: /dev/shm/healthz
  interval: 300
